#!/bin/sh

set -e

DIRS="/var/log/graphite"

case "${1}" in
	purge)
		rm -rf /var/log/graphite
		rm -f /var/lib/graphite/graphite.db

		for i in $DIRS; do
			if dpkg-statoverride --list $i >/dev/null 2>&1; then
				dpkg-statoverride --remove $i
			fi
		done
	;;
	remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
	;;
	*)
		echo "postrm called with unknown argument \`${1}'" >&2
		exit 1
	;;
esac

#DEBHELPER#

exit 0
